name: plus_todo
description: "아이젠아워 매트릭스를 이용한 투두 리스트"

publish_to: 'none'
version: 1.4.3+2

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  gap: ^3.0.1
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.2.1+1
  timezone: ^0.9.4
  auto_size_text: ^3.0.0
  permission_handler: ^11.3.1
  table_calendar: ^3.0.9
  app_settings: ^5.1.1
  package_info_plus: ^8.0.1
  cool_dropdown: ^2.1.0
  flutter_screenutil: ^5.9.3
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
    - family: Itim
      fonts:
        - asset: assets/fonts/itim/Itim-Regular.ttf
          weight: 400